GET http://localhost:3000/orders

###
GET http://localhost:3000/orders/ca4027fc-1f0f-46c9-b987-ad9c21013783

###
POST http://localhost:3000/orders
Content-Type: application/json

{
    "amount": 800
}

###
PATCH http://localhost:3000/orders/ca4027fc-1f0f-46c9-b987-ad9c21013783
Content-Type: application/json

{
    "amount": 700
}

###
DELETE http://localhost:3000/orders/ca4027fc-1f0f-46c9-b987-ad9c21013783

